import {parts,statement,sources} from './content.js';
const $=id=>document.getElementById(id);
const state={mode:'day',view:'perspective',labels:false,smoke:true,auto:false,pan:false,spread:0,visible:Object.fromEntries(parts.map(p=>[p.id,true]))};let engine=null;
function select(id){const p=parts.find(p=>p.id===id);$('part-title').textContent=p.name;$('part-sub').textContent=p.sub;$('traditional').textContent=p.traditional;$('design').textContent=p.design;$('count').textContent=String(parts.indexOf(p)+1).padStart(2,'0')+' / 06';document.querySelectorAll('[data-part]').forEach(b=>b.classList.toggle('active',b.dataset.part===id));}
for(const [i,p]of parts.entries()){const row=document.createElement('div');row.className='layer-row';row.innerHTML=`<button data-part="${p.id}" aria-label="閱讀${p.name}"><span class="partnum">0${i+1}</span><span class="dot" style="background:${p.color}"></span>${p.name}</button><input type="checkbox" role="switch" data-layer="${p.id}" aria-label="顯示${p.name}" checked>`;$('layers').appendChild(row);row.querySelector('button').onclick=()=>select(p.id);row.querySelector('input').onchange=e=>{state.visible[p.id]=e.target.checked;apply();};}
$('statement').textContent=statement;for(const [name,url]of sources){const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noreferrer';a.textContent=name+' ↗';$('sources').appendChild(a);}for(const [v,n]of [['front','前視圖'],['right','右視圖'],['top','上視圖'],['perspective','主視覺'],['night','夜景圖'],['exploded','解構圖']]){const a=document.createElement('a');a.href='./renders/render-'+v+'.png';a.download='龍脈大坑_'+n+'_3200.png';a.textContent=n+' ⇩';$('downloads').appendChild(a);}
function apply(){document.body.dataset.mode=state.mode;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===state.mode)));document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===state.view)));$('rotate').setAttribute('aria-pressed',String(state.auto));$('pan').setAttribute('aria-pressed',String(state.pan));$('labels').checked=state.labels;$('smoke').checked=state.smoke;$('spread').value=state.spread;$('spread-value').textContent=state.spread+'%';$('explode').textContent=state.spread?'重新組合':'展開工藝層次';document.querySelectorAll('[data-layer]').forEach(c=>c.checked=state.visible[c.dataset.layer]);$('fallback').src='./renders/render-'+(state.spread?'exploded':state.mode==='night'?'night':state.view)+'.png';engine?.update(state);}
function view(v){state.view=v;state.auto=false;engine?.view(v);apply();}
function mode(m){state.mode=m;state.spread=m==='craft'?100:0;state.labels=m==='craft';state.auto=false;apply();view('perspective');}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>mode(b.dataset.mode));
$('labels').onchange=e=>{state.labels=e.target.checked;apply();};$('smoke').onchange=e=>{state.smoke=e.target.checked;apply();};$('rotate').onclick=()=>{state.auto=!state.auto;apply();};$('pan').onclick=()=>{state.pan=!state.pan;apply();};$('zoom-in').onclick=()=>engine?.zoom(.88);$('zoom-out').onclick=()=>engine?.zoom(1.14);$('spread').oninput=e=>{const old=state.spread;state.spread=Number(e.target.value);apply();if((old>25)!==(state.spread>25))view('perspective');};$('explode').onclick=()=>{state.spread=state.spread?0:100;state.labels=!!state.spread;apply();view('perspective');};$('reset').onclick=()=>{Object.assign(state,{labels:false,smoke:true,auto:false,pan:false,spread:0,mode:'day',visible:Object.fromEntries(parts.map(p=>[p.id,true]))});select('head');apply();view('perspective');};$('open-notes').onclick=$('footer-notes').onclick=()=>$('notes').showModal();$('close-notes').onclick=()=>$('notes').close();select('head');apply();
import('./engine.js').then(m=>m.createStudio($('stage'),select)).then(e=>{engine=e;apply();$('fallback').hidden=true;$('notice').hidden=true;}).catch(err=>{console.error(err);$('notice').textContent='靜態預覽・此瀏覽器未能啟用 3D。請使用支援 WebGL 2 的瀏覽器自由旋轉，或下載 GLB。';$('gesture').textContent='目前為静態渲染・可切換標準視圖'.replace('静','靜');for(const id of ['rotate','pan','zoom-in','zoom-out','smoke'])$(id).disabled=true;});
const context=document.modelContext;if(context?.registerTool){const life=new AbortController();const register=tool=>Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{});register({name:'read_dragon_state',description:'讀取本頁龍脈模型觀看狀態。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...state,rendering:engine?'interactive_3d':'static_preview'})});register({name:'configure_dragon_view',description:'更改本頁模型的模式、視角或圖層，沒有外部寫入。',inputSchema:{type:'object',properties:{mode:{enum:['day','night','craft']},view:{enum:['front','right','top','perspective']},labels:{type:'boolean'}},additionalProperties:false},execute:async input=>{if(!input||Array.isArray(input)||typeof input!=='object'||Object.keys(input).some(k=>!['mode','view','labels'].includes(k)))throw Error('無效設定');if(input.mode!==undefined&&!['day','night','craft'].includes(input.mode))throw Error('無效模式');if(input.view!==undefined&&!['front','right','top','perspective'].includes(input.view))throw Error('無效視角');if(input.labels!==undefined&&typeof input.labels!=='boolean')throw Error('無效標籤設定');if(input.mode)mode(input.mode);if(input.view)view(input.view);if(input.labels!==undefined){state.labels=input.labels;apply();}return{...state};}});window.addEventListener('pagehide',()=>life.abort(),{once:true});}
