import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {parts} from './content.js';
const V=(x,y,z)=>new T.Vector3(x,y,z);
const offsets={head:V(-2.8,.45,3.6),rope:V(2.25,.25,-1.9),grass:V(-.5,.1,1.4),incense:V(3.1,.4,4.8),moon:V(-3.2,.1,-2.9),base:V(0,0,0)};
const anchors={head:V(-.37,4.98,1.5),rope:V(-1.15595,4.23754,-.40998),grass:V(.71907,1.80647,-.10468),incense:V(1.7095,4.8449,.7321),moon:V(-2.5,4.57,-.55),base:V(1.85,.43,1.8)};
export async function createStudio(host,select){
 const renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.setSize(host.clientWidth,host.clientHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;host.appendChild(renderer.domElement);
 const scene=new T.Scene();let root;
 try{root=(await new GLTFLoader().loadAsync('./model.glb')).scene;}catch(e){renderer.dispose();renderer.domElement.remove();throw e;}
 scene.add(root);const groups=Object.fromEntries(parts.map(p=>[p.id,root.getObjectByName(p.id)]));if(Object.values(groups).some(g=>!g))throw Error('模型圖層不完整');
 root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});for(const p of parts)groups[p.id].traverse(o=>{if(o.isMesh)o.userData.part=p.id;});
 const original=Object.fromEntries(parts.map(p=>[p.id,groups[p.id].position.clone()]));
 const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.04);scene.environment=env.texture;scene.environmentIntensity=.5;room.dispose();
 const hemi=new T.HemisphereLight(0xe5eddf,0x2b271f,1.8);scene.add(hemi);const key=new T.DirectionalLight(0xffdfb0,3.2);key.position.set(-5,10,8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-10,right:10,top:10,bottom:-10,near:.1,far:35});key.shadow.normalBias=.022;key.shadow.bias=-.0003;scene.add(key);const fill=new T.DirectionalLight(0xbbd3df,1.8);fill.position.set(6,5,-3);scene.add(fill);const rim=new T.DirectionalLight(0xffc47c,2.2);rim.position.set(-4,7,-5);scene.add(rim);
 const ground=new T.Mesh(new T.CircleGeometry(80,80),new T.MeshStandardMaterial({color:0x263027,roughness:.91}));ground.rotation.x=-Math.PI/2;ground.position.y=-.005;ground.receiveShadow=true;scene.add(ground);
 const plaque=document.createElement('canvas');plaque.width=512;plaque.height=256;const pc=plaque.getContext('2d');pc.fillStyle='#a87e49';pc.fillRect(0,0,512,256);pc.strokeStyle='#332a1f';pc.lineWidth=8;pc.strokeRect(17,17,478,222);pc.fillStyle='#332a1f';pc.font='bold 140px serif';pc.textAlign='center';pc.textBaseline='middle';pc.fillText('龍脈',256,138);const tex=new T.CanvasTexture(plaque);tex.colorSpace=T.SRGBColorSpace;const seal=new T.Mesh(new T.PlaneGeometry(.59,.27),new T.MeshStandardMaterial({map:tex,metalness:.45,roughness:.55}));seal.position.set(0,.27,2.94);groups.base.add(seal);
 const perspective=new T.PerspectiveCamera(36,1,.1,150),ortho=new T.OrthographicCamera(-5,5,5,-5,.1,150),target=V(0,3.05,.1);let camera=perspective,controls;
 let state={mode:'day',view:'perspective',labels:false,smoke:true,auto:false,pan:false,spread:0,visible:Object.fromEntries(parts.map(p=>[p.id,true]))},spread=0,time=0,disposed=false;
 function configureControl(){controls?.dispose();controls=new OrbitControls(camera,renderer.domElement);controls.target.copy(target);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=state.spread>25?12:7.2;controls.maxDistance=32;controls.minZoom=.6;controls.maxZoom=2.2;controls.minPolarAngle=0;controls.maxPolarAngle=Math.PI/2;controls.autoRotateSpeed=.48;controls.touches.TWO=T.TOUCH.DOLLY_PAN;controls.addEventListener('change',()=>{controls.target.x=T.MathUtils.clamp(controls.target.x,-1.5,1.5);controls.target.y=T.MathUtils.clamp(controls.target.y,2,4.2);controls.target.z=T.MathUtils.clamp(controls.target.z,-1.5,1.5);camera.position.y=Math.max(.15,camera.position.y);});}
 function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);perspective.aspect=w/h;perspective.updateProjectionMatrix();const s=4.25*Math.max(1,h/w);ortho.left=-s*w/h;ortho.right=s*w/h;ortho.top=s;ortho.bottom=-s;ortho.updateProjectionMatrix();}
 function view(v){if(v==='perspective'){camera=perspective;perspective.up.set(0,1,0);perspective.position.set(state.spread>25?13:8.1,state.spread>25?9:6.5,state.spread>25?19:14);if(host.clientWidth/host.clientHeight<.72)perspective.position.multiplyScalar(1.23);}else{camera=ortho;ortho.up.set(0,v==='top'?0:1,v==='top'?-1:0);ortho.zoom=1;ortho.position.copy(v==='front'?V(0,3.05,25):v==='right'?V(25,3.05,0):V(0,28.05,.1));}configureControl();camera.lookAt(target);resize();controls.update();}
 view('perspective');
 const tips=[];root.traverse(o=>{if(o.isMesh&&o.name.includes('香端光點'))tips.push(o);});const points=[];
 // GLB incense caps are merged cylinders. Their centres remain true geometry locations.
 for(const mesh of tips){const g=mesh.geometry,pos=g.getAttribute('position');const stride=34;for(let i=0;i<pos.count;i+=stride){const p=V(0,0,0);let n=0;for(let j=i;j<Math.min(i+stride,pos.count);j++){p.add(V(pos.getX(j),pos.getY(j),pos.getZ(j)));n++;}p.multiplyScalar(1/n);points.push(p);}}
 const flow=new T.CatmullRomCurve3([V(1.9,.8,.6),V(-1.9,4.1,-.4),V(-1.5,5.7,-.6),V(1.4,5.2,.4),V(2,3.6,1),V(.3,1.25,0),V(-1.7,1.8,0),V(-.8,3.2,1.1),V(.18,4.43,1.1)]);const samples=flow.getPoints(160);const phases=points.map(p=>{let best=Infinity,idx=0;samples.forEach((s,i)=>{const d=p.distanceToSquared(s);if(d<best){best=d;idx=i;}});return idx/160;});
 const geo=new T.BufferGeometry().setFromPoints(points);geo.setAttribute('phase',new T.Float32BufferAttribute(phases,1));const glowMat=new T.ShaderMaterial({transparent:true,depthWrite:false,blending:T.AdditiveBlending,uniforms:{time:{value:0},pixel:{value:renderer.getPixelRatio()}},vertexShader:`attribute float phase;uniform float time;uniform float pixel;varying float power;void main(){float pulse=pow(max(0.,cos((phase-fract(time*.085))*6.283185)),16.);power=.24+.76*pulse;vec4 mv=modelViewMatrix*vec4(position,1.);gl_PointSize=clamp((32.+30.*pulse)*pixel/-mv.z,1.,14.);gl_Position=projectionMatrix*mv;}`,fragmentShader:`varying float power;void main(){float d=length(gl_PointCoord-.5)*2.;if(d>1.)discard;gl_FragColor=vec4(1.,.48,.12,pow(1.-d,2.)*power);}`});const glow=new T.Points(geo,glowMat);groups.incense.add(glow);
 const smokeGeo=new T.BufferGeometry().setFromPoints(points.filter((_,i)=>i%Math.max(1,Math.floor(points.length/90))===0).slice(0,90));smokeGeo.setAttribute('seed',new T.Float32BufferAttribute(Array.from({length:smokeGeo.attributes.position.count},(_,i)=>(i*.6180339)%1),1));const smokeMat=new T.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{time:{value:0},pixel:{value:renderer.getPixelRatio()}},vertexShader:`attribute float seed;uniform float time;uniform float pixel;varying float opacity;void main(){float life=fract(time*.1+seed);vec3 p=position;p.y+=life*.8;p.x+=sin(time*.4+seed*36.)*.07*life;vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=(20.+50.*life)*pixel/-mv.z;opacity=sin(life*3.14159)*.09;}`,fragmentShader:`varying float opacity;void main(){float d=length(gl_PointCoord-.5)*2.;if(d>1.)discard;gl_FragColor=vec4(.74,.75,.68,pow(1.-d,2.)*opacity);}`});const smoke=new T.Points(smokeGeo,smokeMat);groups.incense.add(smoke);
 const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('leaders');svg.innerHTML='<defs><marker id="arrow" markerWidth="7" markerHeight="7" refX="1" refY="3.5" orient="auto-start-reverse"><path d="M7 0L0 3.5L7 7" fill="none" stroke="#d6b982"/></marker></defs>';host.appendChild(svg);const labels=parts.map(p=>{const b=document.createElement('button');b.className='part-label';b.textContent=p.name;b.onclick=()=>select(p.id);host.appendChild(b);const line=document.createElementNS(svg.namespaceURI,'line');line.setAttribute('stroke','#d6b982');line.setAttribute('marker-start','url(#arrow)');svg.appendChild(line);return{id:p.id,b,line};});
 function update(next){state={...next};controls.autoRotate=state.auto;controls.minDistance=state.spread>25?12:7.2;controls.mouseButtons.LEFT=state.pan?T.MOUSE.PAN:T.MOUSE.ROTATE;controls.touches.ONE=state.pan?T.TOUCH.PAN:T.TOUCH.ROTATE;for(const p of parts)groups[p.id].visible=state.visible[p.id];const night=state.mode==='night';hemi.intensity=night?.7:1.8;key.intensity=night?1.5:3.2;fill.intensity=night?1.1:1.8;rim.intensity=night?1.5:2.2;scene.environmentIntensity=night?.22:.5;glow.visible=night;smoke.visible=night&&state.smoke;for(const m of tips)m.material.emissiveIntensity=night?4:.18;}
 const ray=new T.Raycaster(),pointer=new T.Vector2();let down=[0,0];renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(Object.values(groups).filter(g=>g.visible),true).find(h=>h.object.isMesh&&h.object.userData.part);if(hit)select(hit.object.userData.part);});
 let last=performance.now();renderer.setAnimationLoop(now=>{if(disposed)return;const dt=Math.min(.05,(now-last)/1000);last=now;time+=dt;spread=T.MathUtils.damp(spread,state.spread/100,4,dt);for(const p of parts)groups[p.id].position.copy(original[p.id]).addScaledVector(offsets[p.id],spread);controls.update();glowMat.uniforms.time.value=smokeMat.uniforms.time.value=time;for(const {id,b,line}of labels){const show=state.labels&&state.visible[id];b.hidden=!show;line.style.display=show?'block':'none';if(!show)continue;const p=anchors[id].clone().addScaledVector(offsets[id],spread).project(camera),ax=(p.x*.5+.5)*host.clientWidth,ay=(-p.y*.5+.5)*host.clientHeight,x=T.MathUtils.clamp(ax+25,20,host.clientWidth-105),y=T.MathUtils.clamp(ay,75,host.clientHeight-95);b.style.left=x+'px';b.style.top=y+'px';line.setAttribute('x1',ax);line.setAttribute('y1',ay);line.setAttribute('x2',x);line.setAttribute('y2',y+14);}renderer.render(scene,camera);});const observer=new ResizeObserver(resize);observer.observe(host);update(state);
 window.addEventListener('pagehide',()=>{disposed=true;renderer.setAnimationLoop(null);observer.disconnect();controls.dispose();env.dispose();pmrem.dispose();renderer.dispose();},{once:true});
 return{update,view,zoom(f){if(camera===perspective){const d=camera.position.clone().sub(controls.target).multiplyScalar(f).clampLength(controls.minDistance,controls.maxDistance);camera.position.copy(controls.target).add(d);}else{ortho.zoom=T.MathUtils.clamp(ortho.zoom/f,.6,2.2);ortho.updateProjectionMatrix();}controls.update();}};
}
